"""
Configuration: API Keys, Model Lists, Output Directories, LaTeX Template Library
"""

import os
from pathlib import Path
from typing import TypedDict, Annotated, List, Dict
import operator

# ── API Keys ──────────────────────────────────────────────────
MINERU_API_KEY  = os.getenv("MINERU_API_KEY",  "")
OLLAMA_API_KEY  = os.getenv("OLLAMA_API_KEY",  "")

# ── Model Configuration ───────────────────────────────────────
OLLAMA_BASE_URL   = os.getenv("OLLAMA_BASE_URL",   "http://localhost:11434/v1")
OLLAMA_MODEL_NAME = os.getenv("OLLAMA_MODEL_NAME", "deepseek-v4-pro:cloud")

MODELS = {
    "ollama": {
        "base_url":   OLLAMA_BASE_URL,
        "api_key":    lambda: OLLAMA_API_KEY,
        "model":      OLLAMA_MODEL_NAME,
        "max_tokens": 20000,
    },
}

# ── Root Output Directory ───────────────────────────────────────
OUTPUT_ROOT = Path(__file__).parent.parent / "output"

# ── LaTeX Template Library ─────────────────────────────────────

class TemplateInfo(TypedDict):
    desc: str
    preamble: str
    body_wrapper: str
    style_hint: str
    detailed_instructions: str

TEMPLATES: Dict[str, TemplateInfo] = {

    "amsart": {
        "desc": "AMS Article — Professional math style with comprehensive theorem environments.",
        "preamble": r"""\documentclass{amsart}
\usepackage{amsmath, amssymb, amsthm}
\usepackage{fontspec}
\usepackage{xeCJK}
\setCJKmainfont{SimSun}
\usepackage{hyperref}
\usepackage{cleveref}

\newtheorem{theorem}{Theorem}[section]
\newtheorem{lemma}[theorem]{Lemma}
\newtheorem{proposition}[theorem]{Proposition}
\newtheorem{corollary}[theorem]{Corollary}
\newtheorem{definition}[theorem]{Definition}
\theoremstyle{remark}
\newtheorem{remark}{Remark}[section]
\newtheorem{example}{Example}[section]

\title{__TITLE__}
\author{Notes}
\date{\today}
""",
        "body_wrapper": r"""\begin{document}
\begin{abstract}
This document was automatically generated by pdf2latex.
\end{abstract}
\maketitle
\tableofcontents
__BODY__
\end{document}
""",
        "style_hint": "Use AMS style: theorem/lemma/definition/remark environments, math in align* or equation.",
        "detailed_instructions": r"""
### AMSART Template Specific Instructions:
1. **Theorem Environments**: Use the following standard environments:
   - \begin{theorem}...\end{theorem} for main results.
   - \begin{lemma}...\end{lemma}, \begin{proposition}...\end{proposition}, \begin{corollary}...\end{corollary} for supporting results.
   - \begin{definition}...\end{definition} for formal definitions.
   - \begin{example}...\end{example} for illustrative examples.
   - \begin{remark}...\end{remark} for comments or observations.
   - \begin{proof}...\end{proof} for proofs (automatically adds QED symbol).
2. **Math Formatting**:
   - Prefer `align*` for unnumbered multi-line equations and `equation` for single-line numbered equations.
   - Use `\mathbf` for bold vectors and `\mathbb` for sets (R, C, N, etc.).
3. **Structure**: 
   - Use `\section` as the primary heading level. 
   - Do NOT use `\chapter` as amsart does not support it.
4. **References**:
   - Use `\cref{...}` for all cross-references to theorems, definitions, and sections.
"""
    },

    "article": {
        "desc": "Standard Article — Clean and general-purpose, suitable for textbook notes.",
        "preamble": r"""\documentclass[12pt, a4paper]{article}
\usepackage{fontspec}
\usepackage{xeCJK}
\setCJKmainfont{SimSun}
\usepackage{amsmath, amssymb, amsthm}
\usepackage{geometry}
\geometry{top=2.5cm, bottom=2.5cm, left=3cm, right=3cm}
\usepackage{hyperref, xcolor, enumitem}
\usepackage{cleveref}

\newtheorem{theorem}{Theorem}[section]
\newtheorem{lemma}[theorem]{Lemma}
\newtheorem{definition}[theorem]{Definition}
\theoremstyle{remark}
\newtheorem*{remark}{Note}

\title{__TITLE__}
\author{Notes}
\date{\today}
""",
        "body_wrapper": r"""\begin{document}
\maketitle
\tableofcontents
\newpage
__BODY__
\end{document}
""",
        "style_hint": "Use standard article style: section/subsection hierarchy, English theorem names.",
        "detailed_instructions": r"""
### Standard Article Template Specific Instructions:
1. **Theorem Environments**:
   - \begin{theorem}...\end{theorem}
   - \begin{lemma}...\end{lemma}
   - \begin{definition}...\end{definition}
   - \begin{remark}...\end{remark} (Note: this is an unnumbered environment).
2. **Structural Levels**:
   - Start with `\section`. 
   - Use `\subsection` and `\subsubsection` for nested content.
3. **Formatting**:
   - Use `itemize` or `enumerate` for lists, with `enumitem` support for custom labeling if needed.
   - Wrap large code or pseudo-code in `verbatim` or `quote` if formatting is critical.
4. **Math**:
   - Standard LaTeX math environments: `\[ ... \]`, `equation`, `align`.
"""
    },

    "ctexart": {
        "desc": "CTeX Article — Best for documents with significant Chinese content.",
        "preamble": r"""\documentclass[12pt, a4paper, UTF8]{ctexart}
\usepackage{amsmath, amssymb, amsthm}
\usepackage{geometry}
\geometry{margin=2.5cm}
\usepackage{hyperref, xcolor}
\usepackage{cleveref}

\newtheorem{theorem}{定理}[section]
\newtheorem{lemma}[theorem]{引理}
\newtheorem{definition}[theorem]{定义}
\newtheorem{example}[theorem]{例}
\theoremstyle{remark}
\newtheorem*{remark}{注记}

\title{__TITLE__}
\author{}
\date{\today}
""",
        "body_wrapper": r"""\begin{document}
\maketitle
\tableofcontents
\newpage
__BODY__
\end{document}
""",
        "style_hint": "Use CTeX style: Chinese environment names, section/subsection hierarchy.",
        "detailed_instructions": r"""
### CTeX Article Template Specific Instructions:
1. **Chinese Environment Names**: 
   - \begin{theorem} renders as "定理".
   - \begin{lemma} renders as "引理".
   - \begin{definition} renders as "定义".
   - \begin{example} renders as "例".
   - \begin{remark} renders as "注记".
2. **Typesetting**:
   - Sections are titled "第1节", etc., automatically.
   - Use standard `\section`, `\subsection` commands.
3. **Math and Symbols**:
   - Mathematical content remains in standard LaTeX notation ($...$).
   - Ensure punctation inside math is consistent with LaTeX standards.
"""
    },

    "beamer": {
        "desc": "Beamer Slides — For creating academic presentations.",
        "preamble": r"""\documentclass{beamer}
\usepackage{fontspec}
\usepackage{xeCJK}
\setCJKmainfont{SimSun}
\usepackage{amsmath, amssymb}
\usetheme{Madrid}
\usecolortheme{default}

\title{__TITLE__}
\author{Notes}
\date{\today}
""",
        "body_wrapper": r"""\begin{document}
\begin{frame}
\titlepage
\end{frame}
\begin{frame}{Contents}
\tableofcontents
\end{frame}
__BODY__
\end{document}
""",
        "style_hint": "Use Beamer style: each key point as a frame, use block environments for emphasis.",
        "detailed_instructions": r"""
### Beamer Presentation Template Specific Instructions:
1. **Frame Structure**:
   - Every slide must be wrapped in a `\begin{frame}{Frame Title} ... \end{frame}`.
   - Do NOT just output text without a frame environment.
2. **Highlighting**:
   - Use `\begin{block}{Block Title} ... \end{block}` for important theorems, definitions, or summaries.
   - Use `\begin{alertblock}{...}` for warnings or critical notes.
   - Use `\begin{exampleblock}{...}` for examples.
3. **Hierarchy**:
   - `\section{...}` and `\subsection{...}` will update the progress bar/sidebar but should be used sparingly between frames.
4. **Lists**:
   - Use `itemize` or `enumerate`. Beamer styles these automatically.
   - Use `\pause` to reveal list items sequentially if appropriate for the content flow.
"""
    },
}

# ── LangGraph State Types ─────────────────────────────────────

class Chapter(TypedDict):
    index: int
    title: str
    level: int
    line_start: int
    line_end: int

class ChapterOutput(TypedDict):
    index: int
    title: str
    latex_body: str

class PipelineState(TypedDict):
    pdf_path:        str
    markdown_path:   str
    template_name:   str
    model_name:      str
    mode:            str   # "notes" | "original"
    doc_title:       str
    doc_type:        str
    output_dir:      str
    chapters:        List[Chapter]
    chapter_outputs: Annotated[List[ChapterOutput], operator.add]
    final_latex:     str

class WriterInput(TypedDict):
    chapter:       Chapter
    markdown_path: str
    all_titles:    List[str]
    template_name: str
    model_name:    str
    mode:          str
    doc_type:      str
    output_dir:    str
